title: Brandon Rodriguez
logo: /Assets/Headshot.png
description: **ABOUT ME** 
*I am an undergraduate student at Stanford University, class of 2027, majoring in mechanical engineering. I possess skills in Fusion 360, Autodesk, MATLAB, Python, tool proficiency, and machining. I have a deep attention to detail when designing, pride myself on my resilience, and love talking about anything related to robotics. I am passionate about advancing the engineering field and helping people in need through my work.
show_downloads: true
theme: jekyll-theme-minimal
